# -*- coding: utf-8 -*-
"""Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ah8mEtAKbR3xA9DvtL4n8jIhpdIBe881
"""

!pip install -q gradio sentence-transformers
print("--- Professional AI Environment Ready ---")

"""
CODTECH IT SOLUTIONS - INTERNSHIP TASK 3
PROJECT: ADVANCED AI CHATBOT WITH NLP (SBERT TRANSFORMERS)
INTERN: [YOUR NAME]
ID: [YOUR INTERN ID]

DESCRIPTION:
An enterprise-grade chatbot utilizing Sentence-BERT (SBERT) for semantic
intent mapping. It calculates the mathematical distance between user
input and a knowledge base to provide contextually accurate responses,
including real-time awareness of date and time.
"""

import gradio as gr
from sentence_transformers import SentenceTransformer, util
import torch
from datetime import datetime

# ============================================================
# 1. AI ENGINE: SEMANTIC TRANSFORMER ARCHITECTURE
# ============================================================
class CodtechIntelligenceBot:
    def __init__(self):
        # Load the industry-standard SBERT model (BERT-based)
        # Translates text into 384-dimensional mathematical vectors.
        self.model = SentenceTransformer('all-MiniLM-L6-v2')

        # Professional Structured Knowledge Base
        self.knowledge_base = {
            "Date_Time": {
                "patterns": ["What is the date today?", "Current time", "Today's date", "What day is it?"],
                "response": "DYNAMIC_TIME_DATE"
            },
            "Greetings": {
                "patterns": ["Hi", "Hello", "Hey", "Good morning", "Is anyone there?"],
                "response": "Greetings! I am the CODTECH AI Assistant. How can I facilitate your requests today?"
            },
            "Python": {
                "patterns": ["What is Python?", "Tell me about Python", "Why is Python used?"],
                "response": "Python is a high-level, interpreted programming language. It is the global industry standard for AI, Data Science, and Enterprise Automation."
            },
            "NLP": {
                "patterns": ["What is NLP?", "Explain Natural Language Processing"],
                "response": "NLP allows me to process human language. I use Bi-Encoder Transformers to calculate semantic similarity between your query and my knowledge base."
            },
            "CODTECH": {
                "patterns": ["What is CODTECH?", "Tell me about this internship", "Who is CODTECH IT SOLUTIONS?"],
                "response": "CODTECH IT SOLUTIONS is an elite technical platform providing hands-on internship experiences in emerging technologies like AI and Full Stack Development."
            },
            "Gratitude": {
                "patterns": ["Thank you", "Thanks", "Much appreciated", "That was helpful"],
                "response": "You are very welcome! It is my pleasure to provide the insights and assistance you need for your professional growth."
            },
            "Exit": {
                "patterns": ["Bye", "Goodbye", "See you later", "Exit", "Quit"],
                "response": "Goodbye! It was a pleasure assisting you. System is now standing by. Have a productive day!"
            }
        }
        self._initialize_engine()

    def _initialize_engine(self):
        """Prepare patterns and pre-calculate vectors for high-speed response."""
        self.all_patterns = []
        self.all_responses = []
        for category in self.knowledge_base.values():
            for p in category["patterns"]:
                self.all_patterns.append(p)
                self.all_responses.append(category["response"])

        # Pre-compute mathematical vectors for the patterns
        self.pattern_vectors = self.model.encode(self.all_patterns, convert_to_tensor=True)

    def respond(self, message, history):
        """Main processing function for semantic intent analysis."""
        # Convert user query to a mathematical vector
        query_vector = self.model.encode(message, convert_to_tensor=True)

        # Calculate Cosine Similarity (The 'Distance' between meanings)
        scores = util.cos_sim(query_vector, self.pattern_vectors)[0]

        # Find the best match
        max_score, index = torch.max(scores, dim=0)

        # Professional Confidence Threshold (0.45)
        if max_score > 0.45:
            response = self.all_responses[index]

            # --- DYNAMIC DATE/TIME LOGIC ---
            if response == "DYNAMIC_TIME_DATE":
                now = datetime.now()
                return f"Today is {now.strftime('%A, %B %d, %Y')}. The current system time is {now.strftime('%H:%M:%S')}."

            return response
        else:
            return "I apologize, but I am not trained on that specific query. Could you please provide more context or rephrase your request?"

# ============================================================
# 2. LAUNCHING THE PROFESSIONAL WEB INTERFACE
# ============================================================
bot = CodtechIntelligenceBot()

demo = gr.ChatInterface(
    fn=bot.respond,
    title="🛡️ CODTECH STRATEGIC AI",
    description="Secure Neural Link | Powered by Deep Learning Transformers (SBERT) | Real-Time Date Awareness Active",
    theme="glass",
    examples=["What is the date today?", "What is Python?", "Tell me about CODTECH"],
)

if __name__ == "__main__":
    demo.launch()

